name: "CI"

on: [push]

jobs:
  test:
    runs-on: "ubuntu-22.04"
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: hello
          POSTGRES_PASSWORD: password
          POSTGRES_DB: kokushiex
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: "actions/checkout@v2"

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      - name: "Prepare environment"
        run: |
          # Modify volume paths in .env and docker-compose.yml to avoid permission issues
          sed -i "s|.:/app|/tmp:/tmp|g" .env*
          sed -i "s|.:/app|/tmp:/tmp|g" docker-compose.yml

      - name: "Run Tests"
        run: |
          ./run ci:test

      - name: "Cleanup"
        run: docker-compose down